/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "DNA" CASCADE;

CREATE TABLE "DNA" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "chain" TEXT NOT NULL,
  "isMutant" BOOLEAN NOT NULL);

